project_id = "workout-app-platform"

[api]
enabled = true
port = 54321
schemas = ["public", "api"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

